#!/bin/bash
# c++ server on boost (ssl)
# chmod +x ./send
# password - uQqPa6vHJtEN
echo "sending..."
scp -r html root@45.143.137.49:/root/serverhttps/
scp -r images root@45.143.137.49:/root/serverhttps/
scp -r keys root@45.143.137.49:/root/serverhttps/
scp -r server root@45.143.137.49:/root/serverhttps/
echo "done"